apiVersion: v1
kind: Service
metadata:
  name: {{ include "uk-platform-helm.fullname" . }}
  labels:
    {{- include "uk-platform-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "uk-platform-helm.selectorLabels" . | nindent 4 }}
